# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 08db66a54189aea8a08cc6941a48bfc8b7a292c4eddcd711d103a25de148e38365175afbbc986804f25ca887ea9cef9739a425b17138a3065c47124156bf577b

test:
  secret_key_base: 41ce1892453f048c1fcaa03334758cd1f699b7f11d904ea01bd6ae68277a70188b9ba70dd87bb1a32bbca9968b385a70d003dfe0f99d18dd3ed2e9ca5429371f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
